[build]
  publish = "public"
  functions = "netlify/functions"

[functions."archive-flags"]
  schedule = "5 3 * * *"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/revision"
  to = "/.netlify/functions/revision"
  status = 200

[[redirects]]
  from = "/api/state"
  to = "/.netlify/functions/state"
  status = 200

[[redirects]]
  from = "/api/change-password"
  to = "/.netlify/functions/change-password"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  from = "/api/history"
  to = "/.netlify/functions/history"
  status = 200

[[redirects]]
  from = "/api/history/*"
  to = "/.netlify/functions/history/:splat"
  status = 200
